credentials:
  username: "00000"
  password: "*****"
download:
  base_path: "./downloads"
  progress_bar: true
  show_existing: true
courses:
  # First semester
  - name: "Cookie2020"
    id: 42
    skip_names: "test\\d"
  # Second semester
  - name: "HackThePlanet"
    id: 1337
    skip_before_date: "2020-01-01"
    skip_after_date: "2020-12-31"

