name: Compile 
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
          npm install -g pkg
          
      - name: Compile executables
        run: npm run compile
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/unifi-webex-dl-*
      
